backend:
  name: github
  repo: azureeen/Blog # Remplace avec ton propre nom de dépôt GitHub
  branch: production # Remplace avec la branche principale de ton dépôt, si ce n'est pas `main`

media_folder: "assets/img/uploads"  # Dossier pour les images téléchargées
public_folder: "/img/uploads"      # URL publique des images

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
